# Generated by Django 3.1.3 on 2020-11-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsv1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
