# Generated by Django 3.1.3 on 2020-11-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsv1', '0002_pic_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
